# numpy tutorial
@sohyunwriter

range, copy, ones, zeros, empty, shape, 

드미트리 지노비에프, <모두의 데이터과학 with 파이썬https://studymake.tistory.com/406


In [1]:
import numpy as np

## make array
# range()
numbers = np.array(range(1,11), copy=True) 
print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


I wonder the difference between copy=True / copy=False.

Below code is to understand the difference.

## copy()

In [2]:
## copy()
arr = np.arange(8).reshape(2,4) # original data
print(arr)

[[0 1 2 3]
 [4 5 6 7]]


In [3]:
arr2 = arr
b = arr[0] # not copy (view)
print(b)

b2 = arr[0].copy() # copy (copied array)
print(b2)

[0 1 2 3]
[0 1 2 3]


In [4]:
b[0] = 10
print(b)
print(arr) # original data also changes because pointing that array b changes

[10  1  2  3]
[[10  1  2  3]
 [ 4  5  6  7]]


In [5]:
b2[0] = 12
print(b2)
print(arr) # original data is not changed, and only copied data is changed

[12  1  2  3]
[[10  1  2  3]
 [ 4  5  6  7]]


## ones(), zeros(), empty(), eye()

In [6]:
# ones(), zeros(), empty() : list or tuple of the rank of array as parameter
# ones()
ones = np.ones([2, 4], dtype=np.float64)
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# zeros()
zeros = np.zeros([2, 4], dtype=np.float64)
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# empty()
empty = np.empty([2, 4], dtype=np.float64)
print(empty) # elements of array is not always zero **

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
# eye(N, M=None, k=0, dtype=np.float) : Return a matrix having 1’s on the diagonal and 0’s elsewhere w.r.t. k.
eye = np.eye(3, k=1)
print(eye)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


# shape, ndim, dtype

In [10]:
# shape, ndim, dtype
arr = np.arange(8).reshape(2,4) # array
print(arr.shape) # shape

(2, 4)


In [11]:
print(arr.ndim) # ndim : dimension of array

2


In [12]:
print(zeros.dtype) # element data type of array

float64


In [13]:
# arange(start, stop, step, dtype=None)
np_numbers = np.arange(2, 5, 0.25)
print(np_numbers)

[2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25 4.5  4.75]


In [14]:
# astype(dtype, casting="unsafe", copy=True)
np_inumbers = np_numbers.astype(np.int)
print(np_inumbers)

[2 2 2 2 3 3 3 3 4 4 4 4]


## reshape()

In [15]:
## transpose, 
temp = np.arange(0, 8).reshape(2,2,2)
print(temp)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [16]:
temp2 = temp.reshape(2, 4)
print(temp2)

[[0 1 2 3]
 [4 5 6 7]]


## transpose()

In [17]:
print(temp2.T)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [18]:
temp = np.array(range(1, 10))
print(temp)
print(temp.T)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


Through above code, we can see there is no change between transpose of data and data when ndim is 1.

when ndim == 1, data.T == data

when ndim >= 2, transpose

## boolean indexing

In [19]:
dirty = np.array([9, 4, 1, -0.01, -0.02, -0.001])
whos_dirty = dirty < 0
print(whos_dirty)

[False False False  True  True  True]


In [20]:
dirty[whos_dirty] = 0
print(dirty)

[9. 4. 1. 0. 0. 0.]


In [21]:
linear = np.arange(-1, 1.1, 0.2)
print(linear)
print((linear <= 0.5) & (linear >= -0.5))

[-1.00000000e+00 -8.00000000e-01 -6.00000000e-01 -4.00000000e-01
 -2.00000000e-01 -2.22044605e-16  2.00000000e-01  4.00000000e-01
  6.00000000e-01  8.00000000e-01  1.00000000e+00]
[False False False  True  True  True  True  True False False False]


# ex) zero mask exercise
ReLU Function. ReLU(x) = max(0, x)
Implement forward & backward path of ReLU.

ReLU Forward : ReLU(x) = max(0, x)
[INPUTS] z : 
[OUTPUTS] out : ReLU(z)

In [22]:
## code

## indexing, slicing

In [23]:
# smart indexing
sap = np.array(["MMM", "ABT", "ABBV", "ACN", "ACE", "ATVI", "ADBE", "ADT"])
print(sap[[1, 2, -1]]) # -1 means the last element

['ABT' 'ABBV' 'ADT']


In [24]:
# smart slicing
sap2d = sap.reshape(2,4)
print(sap2d)
print(sap2d[:, [1]]) # 2 dimension array
print(sap2d[:, 1]) # 1 dimension array

[['MMM' 'ABT' 'ABBV' 'ACN']
 ['ACE' 'ATVI' 'ADBE' 'ADT']]
[['ABT']
 ['ATVI']]
['ABT' 'ATVI']


# ex) train_x, train_y separate

In [26]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [44]:
linear = np.arange(-1, 1.1, 0.2)
print(linear)
print((linear <= 0.5) & (linear >= -0.5))

[-1.00000000e+00 -8.00000000e-01 -6.00000000e-01 -4.00000000e-01
 -2.00000000e-01 -2.22044605e-16  2.00000000e-01  4.00000000e-01
  6.00000000e-01  8.00000000e-01  1.00000000e+00]
[False False False  True  True  True  True  True False False False]


In [27]:
b = np.arange(1, 5)
print(b)

[1 2 3 4]


## Broadcasting (배열에서 벡터 연산)

In [28]:
print(a+b) # vector +, -, *, / vector  -> don't have to use 'for'

[1 3 5 7]


In [29]:
print(a*5) # vector * scalar

[ 0  5 10 15]


In [30]:
noise = np.eye(4) + 0.01 * np.ones((4, ))
print(noise)

[[1.01 0.01 0.01 0.01]
 [0.01 1.01 0.01 0.01]
 [0.01 0.01 1.01 0.01]
 [0.01 0.01 0.01 1.01]]


In [31]:
noise = np.eye(4) + 0.01 * np.random.random([4, 4])
print(np.round(noise, 2))

[[1.   0.01 0.01 0.01]
 [0.01 1.01 0.01 0.01]
 [0.01 0.01 1.   0.  ]
 [0.01 0.01 0.   1.  ]]


## ufnc (벡터화된 유니버셜 함수)
파이썬의 사칙연산과 관계형 연산자의 가능성을 넓힘

In [32]:
# ufnc
stocks = np.array([140.49, 0.97, 40.68, 41.53, 55.7, 57.21, 98.2, 99.19, 109.96, 111.47, 35.71, 36.27, 87.85, 89.11, 30.22, 30.91])
print(stocks)


[140.49   0.97  40.68  41.53  55.7   57.21  98.2   99.19 109.96 111.47
  35.71  36.27  87.85  89.11  30.22  30.91]


In [33]:
stocks = stocks.reshape(8,2).T
print(stocks)

[[140.49  40.68  55.7   98.2  109.96  35.71  87.85  30.22]
 [  0.97  41.53  57.21  99.19 111.47  36.27  89.11  30.91]]


In [34]:
fall = np.greater(stocks[0], stocks[1])
print(fall)

[ True False False False False False False False]


In [35]:
print(sap[fall])

['MMM']


In [36]:
# isnan() : 결측치를 찾을 때 쓰기 좋음
stocks[1, 0] = np.nan # change [1, 0] into nan for exercise
print(np.isnan(stocks))

[[False False False False False False False False]
 [ True False False False False False False False]]


In [37]:
stocks[np.isnan(stocks)] = 0
print(stocks)

[[140.49  40.68  55.7   98.2  109.96  35.71  87.85  30.22]
 [  0.    41.53  57.21  99.19 111.47  36.27  89.11  30.91]]


# where(c, a, b)
논리연산자

In [39]:
# where() : boolean array (c), array (a), arrab (b)
# d[i] = a[i] if c[i] else b[i]
changes = np.where(np.abs(stocks[1] - stocks[0]) > 1.00, stocks[1]-stocks[0], 0)
print(changes)

[-140.49    0.      1.51    0.      1.51    0.      1.26    0.  ]


In [40]:
# nonzero() : return index of element which is not zero
print(sap[np.nonzero(changes)])

['MMM' 'ABBV' 'ACE' 'ADBE']


In [42]:
# same result, but more simple code
print(sap[np.abs(stocks[1] - stocks[0]) > 1.00])

['MMM' 'ABBV' 'ACE' 'ADBE']


# ex) log 계산에서 0 이하 제외 방법

## mean(), sum(), std(), min(), max()

In [43]:
# mean(), sum(), std(), min(), max()
# 주식 중 전체 8개 주식의 평균적인 수준보다 크게 변화된 주식 추출
print(sap[np.abs(stocks[0] - stocks[1]) > np.mean(np.abs(stocks[0] - stocks[1]))])

['MMM']


In [ ]:
# more...